kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{nfs-server.default.svc.cluserIP}}
    path: /

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
