kind: Service
apiVersion: v1
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  selector:
    app: nfs
  ports:
    - name: nfs
      port: 2049
      protocol: TCP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
  labels:
    app: nfs
spec:
  selector:
    matchLabels:
      app: nfs
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: nfs-server
          image: nfs-server:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
          volumeMounts:
            - name: local
              mountPath: "/etc/shared"
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: local-node-storage-claim
